/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from 'zod';
import * as generated from './schemas';
export type PublicDaytype = z.infer<typeof generated.publicDaytypeSchema>;
export type PublicExperiencelevel = z.infer<typeof generated.publicExperiencelevelSchema>;
export type PublicHappiness = z.infer<typeof generated.publicHappinessSchema>;
export type PublicUnit = z.infer<typeof generated.publicUnitSchema>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicClientInvitesRowSchema = z.infer<
	typeof generated.publicClientInvitesRowSchemaSchema
>;
export type PublicClientInvitesInsertSchema = z.infer<
	typeof generated.publicClientInvitesInsertSchemaSchema
>;
export type PublicClientInvitesUpdateSchema = z.infer<
	typeof generated.publicClientInvitesUpdateSchemaSchema
>;
export type PublicClientInvitesRelationshipsSchema = z.infer<
	typeof generated.publicClientInvitesRelationshipsSchemaSchema
>;
export type PublicCoachesRowSchema = z.infer<typeof generated.publicCoachesRowSchemaSchema>;
export type PublicCoachesInsertSchema = z.infer<typeof generated.publicCoachesInsertSchemaSchema>;
export type PublicCoachesUpdateSchema = z.infer<typeof generated.publicCoachesUpdateSchemaSchema>;
export type PublicCoachesRelationshipsSchema = z.infer<
	typeof generated.publicCoachesRelationshipsSchemaSchema
>;
export type PublicDaysRowSchema = z.infer<typeof generated.publicDaysRowSchemaSchema>;
export type PublicDaysInsertSchema = z.infer<typeof generated.publicDaysInsertSchemaSchema>;
export type PublicDaysUpdateSchema = z.infer<typeof generated.publicDaysUpdateSchemaSchema>;
export type PublicDaysRelationshipsSchema = z.infer<
	typeof generated.publicDaysRelationshipsSchemaSchema
>;
export type PublicMusclegroup = z.infer<typeof generated.publicMuscleGroupSchema>;
export type PublicExercisesInsertSchema = z.infer<
	typeof generated.publicExercisesInsertSchemaSchema
>;
export type PublicExercisesUpdateSchema = z.infer<
	typeof generated.publicExercisesUpdateSchemaSchema
>;
export type PublicExercisesRelationshipsSchema = z.infer<
	typeof generated.publicExercisesRelationshipsSchemaSchema
>;
export type PublicLibraryWorkoutsRowSchema = z.infer<
	typeof generated.publicLibraryWorkoutsRowSchemaSchema
>;
export type PublicLibraryWorkoutsInsertSchema = z.infer<
	typeof generated.publicLibraryWorkoutsInsertSchemaSchema
>;
export type PublicLibraryWorkoutsUpdateSchema = z.infer<
	typeof generated.publicLibraryWorkoutsUpdateSchemaSchema
>;
export type PublicLibraryWorkoutsRelationshipsSchema = z.infer<
	typeof generated.publicLibraryWorkoutsRelationshipsSchemaSchema
>;
export type PublicModality = z.infer<typeof generated.publicModalitySchema>;
export type PublicProgramsInsertSchema = z.infer<typeof generated.publicProgramsInsertSchemaSchema>;
export type PublicProgramsUpdateSchema = z.infer<typeof generated.publicProgramsUpdateSchemaSchema>;
export type PublicProgramsRelationshipsSchema = z.infer<
	typeof generated.publicProgramsRelationshipsSchemaSchema
>;
export type PublicWorkoutInstancesRowSchema = z.infer<
	typeof generated.publicWorkoutInstancesRowSchemaSchema
>;
export type PublicWorkoutInstancesInsertSchema = z.infer<
	typeof generated.publicWorkoutInstancesInsertSchemaSchema
>;
export type PublicWorkoutInstancesUpdateSchema = z.infer<
	typeof generated.publicWorkoutInstancesUpdateSchemaSchema
>;
export type PublicWorkoutInstancesRelationshipsSchema = z.infer<
	typeof generated.publicWorkoutInstancesRelationshipsSchemaSchema
>;
export type PublicClientGoal = z.infer<typeof generated.publicClientGoalSchema>;
export type PublicDefaultTrackingField = z.infer<typeof generated.publicDefaultTrackingFieldSchema>;
export type PublicEquipment = z.infer<typeof generated.publicEquipmentSchema>;
export type PublicVariation = z.infer<typeof generated.publicVariationSchema>;
export type PublicExercisesRowSchema = z.infer<typeof generated.publicExercisesRowSchemaSchema>;
export type PublicProgramsRowSchema = z.infer<typeof generated.publicProgramsRowSchemaSchema>;
