name: Build and Push Docker Image

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Repository and Sanitized Branch Name
      id: get-names
      run: |
        # Extract branch name and sanitize it for Docker
        sanitized_branch=$(echo "${{ github.head_ref }}" | tr '/' '-')
        echo "branch=$sanitized_branch" >> $GITHUB_ENV
        echo "repo=${{ github.repository }}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .                         # Build context (root of the repo)
        file: ./docker/Dockerfile                 # Path to the Dockerfile (adjust if not in root)
        push: true                         # Push the image to Docker Hub
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ env.repo }}:${{ env.branch }}
          ${{ secrets.DOCKER_USERNAME }}/${{ env.repo }}:latest