name: Delete Docker Image on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  delete-image:
    runs-on: ubuntu-latest

    steps:
    - name: Get Repository and Sanitized Branch Name
      id: get-names
      run: |
        # Extract branch name and sanitize it for Docker
        sanitized_branch=$(echo "${{ github.head_ref }}" | tr '/' '-')
        echo "branch=$sanitized_branch" >> $GITHUB_ENV
        echo "repo=${{ github.repository }}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Delete Docker Image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ env.repo }}:${{ env.branch }}
        echo "Deleting image: $IMAGE_NAME"

        # Call Docker Hub API to delete the image tag
        curl -s -X DELETE \
          -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
          "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/${{ env.repo }}/tags/${{ env.branch }}/" \
        && echo "Image deleted: $IMAGE_NAME" \
        || echo "Failed to delete image: $IMAGE_NAME"