name: deploy to vercel
on:
  pull_request:
    branches:
      - master
  pull_request_target:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: false
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}